# Generated by Django 2.2.6 on 2019-10-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=9999)),
                ('news_author', models.TextField()),
                ('news_title', models.TextField()),
                ('news_content', models.TextField()),
                ('news_date', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=9999)),
                ('user_name', models.TextField()),
                ('user_surname', models.TextField()),
                ('user_date_of_birth', models.DateField(verbose_name='date of birth')),
            ],
        ),
    ]
