# Generated by Django 2.2.6 on 2019-11-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DL_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=9999)),
                ('course_name', models.TextField()),
                ('course_teacher', models.TextField()),
            ],
        ),
    ]
