# Generated by Django 2.2.6 on 2019-11-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DL_app', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.TextField(default='123456'),
        ),
    ]
