# Generated by Django 2.2.6 on 2019-11-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DL_app', '0003_user_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.TextField()),
                ('course_id', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
