# Generated by Django 2.2.6 on 2019-11-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DL_app', '0004_auto_20191121_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher_courses',
            new_name='TeacherCourses',
        ),
    ]
