# Generated by Django 2.2.6 on 2019-12-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DL_app', '0006_simpleuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='user_surname',
            field=models.TextField(default='K'),
            preserve_default=False,
        ),
    ]
