# Generated by Django 2.2.6 on 2019-12-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DL_app', '0007_simpleuser_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleuser',
            name='user_surname',
        ),
    ]
