# Generated by Django 2.2.6 on 2019-12-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DL_app', '0008_remove_simpleuser_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='user_group',
            field=models.TextField(default='n/a'),
            preserve_default=False,
        ),
    ]
