# Generated by Django 2.2.6 on 2019-12-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DL_app', '0009_simpleuser_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=9999)),
                ('group_name', models.TextField()),
                ('group_curator', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.TextField()),
                ('course_id', models.TextField()),
                ('semester', models.TextField()),
            ],
        ),
    ]
