# Generated by Django 2.2.6 on 2019-12-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DL_app', '0010_group_groupcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
