# Generated by Django 2.2.6 on 2019-12-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DL_app', '0011_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherCourses',
        ),
    ]
