# Generated by Django 2.2.6 on 2019-12-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DL_app', '0013_teachercourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.TextField()),
                ('schedule_date', models.DateField()),
                ('course_id', models.TextField()),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.TextField()),
                ('task_name', models.TextField()),
                ('task_description', models.TextField()),
                ('task_files', models.FileField(upload_to='uploads/')),
                ('task_deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.TextField()),
                ('schedule_id', models.TextField()),
                ('is_was', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.TextField()),
                ('task_id', models.TextField()),
                ('score', models.FloatField()),
                ('files', models.FileField(upload_to='')),
                ('time', models.DateField()),
            ],
        ),
    ]
